In [42]:
import numpy as np

In [43]:
L = 5
delta_x = L/10

In [44]:
M = L-2
dim_A = M**2
A = np.zeros((dim_A, dim_A))
for i in range(dim_A):
    A[i,i] = -4
    if i+1<dim_A:
        A[i+1, i] = 1
        A[i, i+1] = 1
    if L-2+i < dim_A:
        A[L-2+i, i] = 1
        A[i, L-2+i] = 1
for m in range(1,L-2):
        A[m*M, m*M-1] = 0
        A[m*M-1, m*M] = 0
print(A)

[[-4.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1. -4.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  1. -4.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0. -4.  1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1. -4.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  1. -4.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0. -4.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  1. -4.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  1. -4.]]


In [45]:
b = np. zeros(dim_A)

In [46]:
x_0 = np.zeros(dim_A)
for i in range(M):
    x_0[(i-1)*M] = 1000

In [54]:
def Jacobi_relaxation(A, b, x_0, epsilon_max = 0.001):
    x = x_0
    D = np.diag(np.diag(A))
    D_inv = np.linalg.inv(D)
    L = np.tril(A, -1)
    R = np.triu(A, 1)
    J = np.matmul(D_inv, D-A)
    epsilon_mat = np.ones(M**2)
    num_iterations = 0
    while np.max(epsilon_mat)>epsilon_max:
        x = np.matmul(D_inv,b) + np.matmul(J,x)
        for r, err in enumerate(epsilon_mat):
            epsilon_mat[r] = np.abs(x[r]-0.25*(x[r+M]+x[r-M]+x[r+1]+x[r-1]))
        num_iterations += 1
    return x, num_iterations, np.max(epsilon_mat), np.mean(epsilon_mat)

x_end, num_iter, err_max, err_mean = Jacobi_relaxation(A,b, x_0)
print(num_iter)

IndexError: index 9 is out of bounds for axis 0 with size 9